use_frameworks!

platform :ios, '10.0'

target 'Artisan_Example' do
  pod 'Artisan', :path => '../'

  target 'Artisan_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 4.0.0'
    pod 'Nimble', '~> 9.2.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 9.1.0'
  end
end
